### ISSUE TITLE
ieo.py - convertespatotiles

### ISSUE THREAD

**Issue by JRGZ** [DrGuy/ieo#9]
When creating the NDVI/EVI files the ENVIFile function defaults the output folder to the folder in the ieo.ini (calling ENVIfile within calvics lines 989 and 993 in ieo.py), this leads to the importespatotiles function not being able to find the evifile and ndvifile variables in lines 1456 and 1457 (the files are expected in the projection folder in the decompressed product).

**Comment by DrGuy** [comment]
Some discrepancies were discovered between IEO-calculated NDVI and NBR vs. those calculated on the fly via Numpy. This might be due to the scaling and type conversion from float to signed 16-bit integer. However, it's now recommended to import data from Landsat and Sentinel-2 without calculating indices.
